import prop1 from "@/assets/prop-1.jpg";
import prop2 from "@/assets/prop-2.jpg";
import prop3 from "@/assets/prop-3.jpg";
import prop4 from "@/assets/prop-4.jpg";
import srinagar from "@/assets/city-srinagar.jpg";
import jammu from "@/assets/city-jammu.jpg";
import gulmarg from "@/assets/city-gulmarg.jpg";
import pahalgam from "@/assets/city-pahalgam.jpg";
import sonmarg from "@/assets/city-sonmarg.jpg";

export const cities = [
  { name: "Srinagar", count: 1240, image: srinagar },
  { name: "Jammu", count: 980, image: jammu },
  { name: "Gulmarg", count: 210, image: gulmarg },
  { name: "Pahalgam", count: 165, image: pahalgam },
  { name: "Sonmarg", count: 95, image: sonmarg },
];

export const properties = [
  {
    id: "jkp-001",
    title: "Modern Wooden Villa with Garden",
    city: "Srinagar",
    area: "Rajbagh",
    price: 18500000,
    priceLabel: "₹1.85 Cr",
    type: "Villa",
    purpose: "Buy",
    beds: 4,
    baths: 3,
    sqft: 3200,
    image: prop1,
    gallery: [prop1, prop2, prop4],
    verified: true,
    featured: true,
    furnished: true,
    readyToMove: true,
    dealer: { name: "Valley Estates", phone: "+91 98000 11111", verified: true },
    amenities: ["Parking", "Garden", "Power Backup", "Wood Interiors", "Security"],
    description: "An exquisitely crafted wooden villa in the heart of Rajbagh. Spacious living, premium interiors and a manicured garden — built for families who value warmth and craftsmanship.",
  },
  {
    id: "jkp-002",
    title: "Premium 3BHK Apartment near Boulevard",
    city: "Srinagar",
    area: "Dalgate",
    price: 9500000,
    priceLabel: "₹95 L",
    type: "Apartment",
    purpose: "Buy",
    beds: 3,
    baths: 2,
    sqft: 1450,
    image: prop2,
    gallery: [prop2, prop1, prop4],
    verified: true,
    featured: true,
    readyToMove: true,
    dealer: { name: "Dal View Realty", phone: "+91 98000 22222", verified: true },
    amenities: ["Lift", "Parking", "Gym", "24x7 Security", "Power Backup"],
    description: "Light-filled 3BHK steps from Boulevard Road with serene lake-view balconies and high-grade finishes.",
  },
  {
    id: "jkp-003",
    title: "Residential Plot — 1 Kanal Mountain View",
    city: "Pahalgam",
    area: "Lidder Valley",
    price: 6500000,
    priceLabel: "₹65 L",
    type: "Plot",
    purpose: "Buy",
    beds: 0,
    baths: 0,
    sqft: 5445,
    image: prop3,
    gallery: [prop3],
    verified: true,
    dealer: { name: "Lidder Lands", phone: "+91 98000 33333", verified: true },
    amenities: ["Road Access", "Clear Title", "Mountain View", "Water"],
    description: "Pristine 1-kanal plot with unobstructed Himalayan views. Verified title, road-ready.",
  },
  {
    id: "jkp-004",
    title: "Glass-Front Commercial Showroom",
    city: "Jammu",
    area: "Gandhi Nagar",
    price: 45000,
    priceLabel: "₹45,000/mo",
    type: "Commercial",
    purpose: "Rent",
    beds: 0,
    baths: 2,
    sqft: 1800,
    image: prop4,
    gallery: [prop4, prop2],
    verified: true,
    featured: true,
    dealer: { name: "Jammu Commercial", phone: "+91 98000 44444", verified: true },
    amenities: ["Glass Facade", "Parking", "Power Backup", "Corner Plot", "High Footfall"],
    description: "Prime corner showroom on Gandhi Nagar high street. Floor-to-ceiling glass, ready to fit-out.",
  },
  {
    id: "jkp-005",
    title: "Furnished 2BHK for Rent",
    city: "Jammu",
    area: "Trikuta Nagar",
    price: 22000,
    priceLabel: "₹22,000/mo",
    type: "Apartment",
    purpose: "Rent",
    beds: 2,
    baths: 2,
    sqft: 1100,
    image: prop2,
    gallery: [prop2, prop1],
    verified: true,
    furnished: true,
    readyToMove: true,
    dealer: { name: "Trikuta Homes", phone: "+91 98000 55555", verified: true },
    amenities: ["Furnished", "Lift", "Parking", "24x7 Water", "Security"],
    description: "Fully furnished 2BHK in a gated society. Move-in ready with appliances and modular kitchen.",
  },
  {
    id: "jkp-006",
    title: "Heritage Chalet on Hilltop",
    city: "Gulmarg",
    area: "Tangmarg Road",
    price: 32500000,
    priceLabel: "₹3.25 Cr",
    type: "Villa",
    purpose: "Buy",
    beds: 5,
    baths: 4,
    sqft: 4200,
    image: prop1,
    gallery: [prop1, prop4],
    verified: true,
    featured: true,
    furnished: true,
    dealer: { name: "Alpine Estates", phone: "+91 98000 66666", verified: true },
    amenities: ["Fireplace", "Garden", "Mountain View", "Wood Interiors", "Heated Floors"],
    description: "An iconic chalet overlooking the meadows of Gulmarg. Hand-crafted woodwork and panoramic views.",
  },
];

export const formatINR = (n) =>
  n >= 10000000
    ? `₹${(n / 10000000).toFixed(2)} Cr`
    : n >= 100000
      ? `₹${(n / 100000).toFixed(1)} L`
      : `₹${n.toLocaleString("en-IN")}`;
